// StockMarket.Client/src/app/stock-chart/stock-chart.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CompanyService } from '../company.service';
import { NgApexchartsModule } from 'ng-apexcharts';
import { ApexAxisChartSeries, ApexChart, ApexXAxis, ApexYAxis, ApexTitleSubtitle, ApexDataLabels, ApexStroke, ApexTooltip, ApexPlotOptions } from 'ng-apexcharts';

// Define ChartOptions interface directly as a fallback
export type ChartOptions = {
  series: ApexAxisChartSeries;
  chart: ApexChart;
  xaxis: ApexXAxis;
  yaxis: ApexYAxis | ApexYAxis[];
  title: ApexTitleSubtitle;
  dataLabels: ApexDataLabels;
  stroke: ApexStroke;
  tooltip: ApexTooltip;
  plotOptions: ApexPlotOptions;
  // annotations: ApexAnnotations; // Removed
};

// Define ChartOptions interface if not already defined by ng-apexcharts
// export type ChartOptions = {
//   series: ApexAxisChartSeries;
//   chart: ApexChart;
//   xaxis: ApexXAxis;
//   yaxis: ApexYAxis | ApexYAxis[];
//   title: ApexTitleSubtitle;
//   dataLabels: ApexDataLabels;
//   stroke: ApexStroke;
//   tooltip: ApexTooltip;
//   plotOptions: ApexPlotOptions;
//   annotations: ApexAnnotations;
// };

@Component({
  selector: 'app-stock-chart',
  standalone: true,
  imports: [CommonModule, FormsModule, NgApexchartsModule],
  templateUrl: './stock-chart.component.html',
  styleUrl: './stock-chart.component.css'
})
export class StockChartComponent implements OnInit {
  searchQuery: string = '';
  companies: any[] = [];
  selectedCompany: any = null;
  marPriceData: any[] = [];
  selectedPeriod: string = '1y';

  public chartOptions: Partial<ChartOptions> | any; // Use Partial<ChartOptions> for flexibility

  constructor(private companyService: CompanyService) {
    this.chartOptions = {
      series: [{
        data: []
      }],
      chart: {
        type: 'candlestick',
        height: 350
      },
      title: {
        text: 'Candlestick Chart',
        align: 'left'
      },
      xaxis: {
        type: 'datetime'
      },
      yaxis: {
        tooltip: {
          enabled: true
        }
      }
    };
  }

  ngOnInit(): void {
  }

  onSearchCompany(): void {
    if (this.searchQuery.length > 2) { // Search only if query is at least 3 characters
      this.companyService.getCompanies(this.searchQuery, 1, 10, '', '')
        .subscribe(response => {
          this.companies = response.companies;
          this.selectedCompany = null; // Clear selected company
          this.marPriceData = []; // Clear previous chart data
          this.updateChartSeries([]); // Clear chart
        });
    } else {
      this.companies = [];
      this.selectedCompany = null;
      this.marPriceData = [];
      this.updateChartSeries([]);
    }
  }

  selectCompany(company: any): void {
    this.selectedCompany = company;
    this.companies = []; // Clear search results
    this.loadMarPriceData(company.compCd);
  }

  loadMarPriceData(compCd: number): void {
    this.companyService.getMarPriceData(compCd, this.selectedPeriod) // Assuming you add this method to CompanyService
      .subscribe(data => {
        this.marPriceData = data;
        this.updateChartSeries(data);
      }, error => {
        console.error('Error loading market price data:', error);
        this.marPriceData = [];
        this.updateChartSeries([]);
      });
  }

  onPeriodChange(period: string): void {
    this.selectedPeriod = period;
    if (this.selectedCompany) {
      this.loadMarPriceData(this.selectedCompany.compCd);
    }
  }

  updateChartSeries(data: any[]): void {
    const seriesData = data.map(item => {
      return {
        x: new Date(item.transDt),
        y: [item.open, item.high, item.low, item.close]
      };
    });

    this.chartOptions = {
      ...this.chartOptions,
      series: [{
        data: seriesData
      }],
      title: {
        text: this.selectedCompany ? `${this.selectedCompany.compNm} Candlestick Chart` : 'Candlestick Chart',
        align: 'left'
      }
    };
  }
}
<div class="container mt-4">
    <h2>Stock Chart</h2>

    <div class="mb-3">
        <input type="text" class="form-control" placeholder="Search Company by Name, Code, ISIN, or Instrument" [(ngModel)]="searchQuery" (keyup)="onSearchCompany()">
    </div>

    <div *ngIf="companies.length > 0" class="list-group mb-3">
        <a *ngFor="let company of companies" href="#" class="list-group-item list-group-item-action" (click)="selectCompany(company); $event.preventDefault()">
            {{ company.compNm }} ({{ company.compCd }}) - {{ company.isinCd }}
        </a>
    </div>

    <div *ngIf="selectedCompany" class="card mb-3">
        <div class="card-header">
            Selected Company: {{ selectedCompany.compNm }} ({{ selectedCompany.compCd }})
        </div>
        <div class="card-body">
            <p><strong>ISIN CD:</strong> {{ selectedCompany.isinCd }}</p>
            <p><strong>Instrument Code:</strong> {{ selectedCompany.instrCd }}</p>
            <!-- Add more company info here if needed -->
        </div>
    </div>

    <div *ngIf="selectedCompany" class="mb-3">
        <label for="period-select" class="form-label">Select Period:</label>
        <select id="period-select" class="form-select" [ngModel]="selectedPeriod" (ngModelChange)="onPeriodChange($event)">
            <option value="1y">1 Year</option>
            <option value="2y">2 Years</option>
            <option value="5y">5 Years</option>
            <option value="all">All</option>
        </select>
    </div>

    <div class="chart-container" *ngIf="marPriceData.length > 0">
        <apx-chart
            [series]="chartOptions.series"
            [chart]="chartOptions.chart"
            [xaxis]="chartOptions.xaxis"
            [title]="chartOptions.title"
            [yaxis]="chartOptions.yaxis"
        ></apx-chart>
    </div>

    <div *ngIf="selectedCompany && marPriceData.length === 0" class="alert alert-info">
        No market price data available for {{ selectedCompany.compNm }}.
    </div>
</div>

// stockmarket.react.client/src/StockChart.js
import React, { useState, useEffect, useMemo } from 'react';
import Chart from 'react-apexcharts'; // Import ApexCharts
import { getCompanies, getMarPriceData } from './api';

const StockChart = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [companies, setCompanies] = useState([]);
  const [selectedCompany, setSelectedCompany] = useState(null);
  const [marPriceData, setMarPriceData] = useState([]);
  const [selectedPeriod, setSelectedPeriod] = useState('1y');

  const handleSearch = async () => {
    if (searchQuery.length > 2) {
      try {
        const response = await getCompanies(searchQuery);
        setCompanies(response.data.companies);
      } catch (error) {
        console.error('Error fetching companies:', error);
      }
    }
  };

  const handleSelectCompany = (company) => {
    setSelectedCompany(company);
    setCompanies([]);
    fetchMarPriceData(company.compCd, selectedPeriod);
  };

  const fetchMarPriceData = async (compCd, period) => {
    try {
      const response = await getMarPriceData(compCd, period);
      console.log("Raw API response data:", response.data);
      // Transform data for ApexCharts candlestick
      const chartData = response.data.map(item => ({
        x: new Date(item.transDt).getTime(), // ApexCharts expects timestamp
        y: [item.open, item.high, item.low, item.close]
      }));
      setMarPriceData(chartData);
    } catch (error) {
      console.error('Error fetching market price data:', error);
    }
  };

  const handlePeriodChange = (e) => {
    const period = e.target.value;
    setSelectedPeriod(period);
    if (selectedCompany) {
      fetchMarPriceData(selectedCompany.compCd, period);
    }
  };

  // ApexCharts options
  const chartOptions = useMemo(() => ({
    chart: {
      type: 'candlestick',
      height: 350,
      background: '#253248',
      foreColor: 'rgba(255, 255, 255, 0.9)',
    },
    title: {
      text: 'Candlestick Chart',
      align: 'left',
      style: {
        color: 'rgba(255, 255, 255, 0.9)'
      }
    },
    xaxis: {
      type: 'datetime',
      tickPlacement: 'on',
      labels: {
        style: {
          colors: 'rgba(255, 255, 255, 0.7)'
        }
      }
    },
    yaxis: {
      tooltip: {
        enabled: true
      },
      labels: {
        style: {
          colors: 'rgba(255, 255, 255, 0.7)'
        }
      }
    },
    grid: {
      borderColor: '#334158'
    },
    plotOptions: {
      candlestick: {
        colors: {
          upward: '#00B746',
          downward: '#EF403C'
        }
      }
    }
  }), []);

  // ApexCharts series data
  const series = useMemo(() => [{
    name: 'Candlestick',
    data: marPriceData,
  }], [marPriceData]);

  return (
    <div className="container mt-4">
      <h2>Stock Chart</h2>
      <div className="mb-3">
        <input
          type="text"
          className="form-control"
          placeholder="Search Company by Name, Code, ISIN, or Instrument"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          onKeyUp={handleSearch}
        />
      </div>

      {companies.length > 0 && (
        <div className="list-group mb-3">
          {companies.map(company => (
            <a
              href="#"
              key={company.id}
              className="list-group-item list-group-item-action"
              onClick={(e) => { e.preventDefault(); handleSelectCompany(company); }}
            >
              {company.compNm} ({company.compCd}) - {company.isinCd}
            </a>
          ))}
        </div>
      )}

      {selectedCompany && (
        <div className="card mb-3">
          <div className="card-header">
            Selected Company: {selectedCompany.compNm} ({selectedCompany.compCd})
          </div>
          <div className="card-body">
            <p><strong>ISIN CD:</strong> {selectedCompany.isinCd}</p>
            <p><strong>Instrument Code:</strong> {selectedCompany.instrCd}</p>
          </div>
        </div>
      )}

      {selectedCompany && (
        <div className="mb-3">
          <label htmlFor="period-select" className="form-label">Select Period:</label>
          <select id="period-select" className="form-select" value={selectedPeriod} onChange={handlePeriodChange}>
            <option value="1y">1 Year</option>
            <option value="2y">2 Years</option>
            <option value="5y">5 Years</option>
            <option value="all">All</option>
          </select>
        </div>
      )}

      {marPriceData.length > 0 && (
        <div className="chart-container">
          <Chart options={chartOptions} series={series} type="candlestick" height={350} />
        </div>
      )}

      {selectedCompany && marPriceData.length === 0 && (
        <div className="alert alert-info">
          No market price data available for {selectedCompany.compNm}.
        </div>
      )}
    </div>
  );
};

export default StockChart;
